import Foundation

struct MarkdownExporter {
    @MainActor
    func export(record: MeetingRecord, aiOutput: AIOutput, rawTranscript: String) throws -> URL {
        let vault = SettingsStore.shared.vaultURL
        try FileManager.default.createDirectory(at: vault, withIntermediateDirectories: true)

        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        let dateStr = formatter.string(from: record.startTime)
        formatter.dateFormat = "HH-mm"
        let timeStr = formatter.string(from: record.startTime)

        let filename = "\(dateStr)_\(timeStr)_\(record.title.sanitizedForFilename).md"
        let fileURL = vault.appendingPathComponent(filename)

        var tags = ["meeting"]
        if record.title.lowercased().contains("standup") { tags.append("standup") }
        if record.title.lowercased().contains("review") { tags.append("review") }

        let takeawaysBlock = aiOutput.keyTakeaways
            .map { "- \($0)" }
            .joined(separator: "\n")

        let actionItemsBlock = aiOutput.actionItems.map { item -> String in
            var line = "- [ ] \(item.task)"
            if let owner = item.owner, !owner.isEmpty {
                line += " (Owner: \(owner))"
            }
            return line
        }.joined(separator: "\n")

        let yaml = """
---
date: \(ISO8601DateFormatter().string(from: record.startTime))
duration: "\(record.formattedDuration)"
title: "\(record.title.replacingOccurrences(of: "\"", with: "\\\""))"
tags: [\(tags.map { "\"\($0)\"" }.joined(separator: ", "))]
source_language: \(SettingsStore.shared.sourceLanguage)
target_language: \(SettingsStore.shared.targetLanguage)
---

# \(record.title)

## Executive Summary

\(aiOutput.executiveSummary)

## Key Takeaways & Action Items

### Takeaways
\(takeawaysBlock)

### Action Items
\(actionItemsBlock)

## Detailed Notes

\(aiOutput.detailedNotes)

## Translated Transcript

\(aiOutput.translatedTranscript)

## Raw Original Transcript

\(rawTranscript)

---
*Generated by Glyph*
"""

        try yaml.write(to: fileURL, atomically: true, encoding: .utf8)
        return fileURL
    }
}

private extension String {
    var sanitizedForFilename: String {
        let invalid = CharacterSet(charactersIn: "/\\?%*|\"<>")
        return self.components(separatedBy: invalid).joined(separator: "_").replacingOccurrences(of: " ", with: "_")
    }
}
